### ISSUE TITLE
Offline export and other function in 2.1.24 dev still busy

### ISSUE THREAD

**Issue by djzippo** [nilsteampassnet/TeamPass#1066]
Hi,
I'm trying the 2.1.24 dev.
I confirm now the import from keepass work.
Other problem is the creation of user (it still busy on creation mask and you don't understand if it created or not) and offline export (still busy on generation as printscreen show but never ending).
Also in information tab, it show current version as 2.1.22  (not 2.1.23) and installed version as 2.1.24.

![offline_generation](https://cloud.githubusercontent.com/assets/7601613/10689616/ec4b2048-797c-11e5-8953-7babe98f0b2d.JPG)

**Comment by nilsteampassnet** [comment]
Thank You for your feedback concerning 2.1.24.

You identified a bug concerning the USer creation. I will commit the
correction.

Concerning the export to offline mode, I've several tries and could not
reproduce.
Can you please use Firebug, and activate its console.
Then launch the export feature, and copy here the result of the query.

Thanks



​

**Comment by djzippo** [comment]
Thank you for work.

I've enabled firebug and I receive a error 500

POST http://**********/sources/export.queries.php
	
500 Internal Server Error
		84ms	
jquery.js (riga 8706)
IntestazioniPostHTMLCookie
Visualizza come testo semplice
Cache-Control	
no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection	
close
Content-Length	
0
Content-Type	
text/html; charset=utf-8
Date	
Fri, 23 Oct 2015 12:17:48 GMT
Expires	
Thu, 19 Nov 1981 08:52:00 GMT
Pragma	
no-cache
Server	
Apache/2.4.7 (Ubuntu)
Visualizza come testo semplice
Accept	
application/json, text/javascript, */*; q=0.01
Accept-Encoding	
gzip, deflate
Accept-Language	
it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
Content-Length	
55
Content-Type	
application/x-www-form-urlencoded; charset=UTF-8
Cookie	
PHPSESSID=o4ugrloda54aoe7v6dbtlpcjq0; jstree_select=17; jstree_open=%23li_2%2C%23li_4%2C%23li_33; jstree_load
=%23li_6%2C%23li_20; KEY_PHPSESSID=IaUfqHFDasrwgYUHHfYPFqdyX1dLXguX5bCznw51w30%3D%3ANn652be%2B6uitSZyNL0Oz8sB2dxgjlOqQSeLS4Gek
%2F8U%3D
Host	
**********
Referer	
http://**********/index.php?page=items
User-Agent	
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
X-Requested-With	
XMLHttpRequest

**Comment by djzippo** [comment]
Server side this is the log:

[23/Oct/2015:14:22:39 +0200] "POST /sources/export.queries.php HTTP/1.1" 500 - "http://*********/index.php?page=items" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"

**Comment by nilsteampassnet** [comment]
Unfortunately , those logs are not really useful.

Please follow instructions [here](http://teampass.net/2014-02-09-how-to-communicate-an-error-log/)

**Comment by djzippo** [comment]
Copy response body is empty for me, it can be the reason because it never end.
Here is location with parameter:
http://******.*****.***/sources/export.queries.php?type=export_to_html_format&ids=17&pdf_password=asdasd

**Comment by nilsteampassnet** [comment]
​On 2.1.24 pre-prod I just tried it and​ could not reproduce.

Can you foward the errors from server. I mean the answer from the server
when using Firebug extension.

**Comment by djzippo** [comment]
The server answer is 500 so this is the only answer I get. Let me know if you want to connect, I can create a user for you.

POST http://*****.*****.***/sources/export.queries.php
500 Internal Server Error
		57ms	
jquery.js (riga 8706)

Intestazioni di risposta
Cache-Control	
no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection	
close
Content-Length	
0
Content-Type	
text/html; charset=utf-8
Date	
Mon, 09 Nov 2015 13:04:37 GMT
Expires	
Thu, 19 Nov 1981 08:52:00 GMT
Pragma	
no-cache
Server	
Apache/2.4.7 (Ubuntu)

Intestazioni di richiesta
Accept	
application/json, text/javascript, */*; q=0.01
Accept-Encoding	
gzip, deflate
Accept-Language	
it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
Content-Length	
53
Content-Type	
application/x-www-form-urlencoded; charset=UTF-8
Cookie	
jstree_select=17; KEY_PHPSESSID=UBMP5P4xuL9pKijk8ekccxUA4GHCdsPZsPRTUJs9tzE%3D%3A4LbBw2Ff2NTl6xPMXgYWCYH1eZci7MBPxOmZ
%2Fh2nrTo%3D; PHPSESSID=e59gr5sabbc55pt0ogq0fmv594
Host	
*****.*****.***
Referer	
http://*****.*****.***/index.php?page=items
User-Agent	
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
X-Requested-With	
XMLHttpRequest

**Comment by djzippo** [comment]
I have also this on management of users, so ther'is something not clean in database.
I try to reinstall the 2.1.24 from zero.

DataTables warning: table id=t_users - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by djzippo** [comment]
No good news. Installed from zero and same problem for export.
maybe too much right requested? Also the file permission -rwxr----- is really dangerous.
Wait to try with production version if something change and hope for a restriction on permission requested.

**Comment by nilsteampassnet** [comment]
​​Can you give me the context of the error you get on table users?
Because I can't reproduce even when creating new instance from scratch.
Perhaps do you need to reup the files?

Same for the export feature, cannot reproduce.
Yes perhaps a right access on the "files" folder to be reworked.
Of course​, this folder needs to have correct permission for the "apache"
user and read access to permit a Teampass user to access and download the
file.

**Comment by djzippo** [comment]
After installed from scratch, the table user is ok.
For the export, the problem is still here.
The permission is ok, the check on install is ok and the installer is be able to alter all permission.
Is possibile to manually generate export file? I can give you credential for teamviewer session (via pm) or credential to access to frontend.

**Comment by mvdboogaard** [comment]
I have the same problem with exporting for Offline usage. 
I notice when you enter a "very strong" password you don't get the HTTP 500 error, but you get a HTTP 200 reponse. Still it will not generate a download link.

**Comment by alinos38** [comment]
Hello,
I have the same error message 
DataTables warning: table id=t_users - Invalid JSON response
I have reinstalled and again the same error message.
Could you please help?

**Comment by nilsteampassnet** [comment]
@alinos38 This has been fixed since release 2.1.24.1

You can get the latest release [HERE](https://github.com/nilsteampassnet/TeamPass/releases/latest).

**Comment by alinos38** [comment]
Hello,

I'm afraid but this error has not been fixed as you can see on copy screen:

Alinos

2015-11-29 18:26 GMT+01:00 Nils Laumaillé <notifications@github.com>:

**Comment by OSAccount** [comment]
Yep, error not fixed in 2.1.24.4

**Comment by djzippo** [comment]
Confirm, not fixed (fresh install).
Problem http 500 (so still busy) also when login with duo authentication.

**Comment by ElGranLoky** [comment]
Confirm, not fixed (fresh install).
Problem http 500 (so still busy) also when login with duo authentication.

**Comment by zendmannet** [comment]
I had the same problem. There is an simple workaround. Just duplicate the includes/libraries/Encryption and rename the folder to encryption.

I'll try to send an pull request when i got time to search for this problem.

**Comment by necarnot** [comment]
Hi,

I can confirm zendmannet's workaround is working with 2.1.25

**Comment by uucom** [comment]
We consistently experienced page-load failure with offline mode and profile panes hanging. Upgraded from 2.1.22, to 23, to 24, to 25, finally to 2.1.26.8, testing each installation, which all failed to load, debug mode detected security policy errors (mixing insecure http and https elements AND different url's). We determined that TeamPass calls certain paths and url's saved in MySQL table _misc, and discovered many artifacts from previous installations. Edited (manually) about a half-dozen records that were not the correct URL or https, and now everything works as expected!  This is likely to be a problem for anybody upgrading or migrating servers, as the misconfigured records will just follow any upgrade or backup-restore.

**Comment by uucom** [comment]
Further work revealed the _misc table contained a complete set of duplicate config records (some old and some new) making the system unstable. This is because _misc contains not only application preferences, but also defines some system preferences in absolute and relative path urls (which can optionally be changed during a migration). In any event, to restore, you must start with a running install of TeamPass and log in as admin, so the _misc table would already be built and the correct directory paths added by the install script. Restore then adds a complete set of duplicate config records into the _misc table (with potential conflicts). The solution (I think) would be to separate _misc into different tables (1) with system configuration info of absolute and relative directory paths (defined by the installation script at the time of installation and editable in preferences as it is now) and another (2) with the application preferences, so application preferences can be cleanly restored (drop-create) while preserving the current system configuration it is running on.
