### ISSUE TITLE
Cannot login in after fresh install

### ISSUE THREAD

**Issue by robmorin** [nilsteampassnet/TeamPass#1731]
### Steps to reproduce
1. git clone https://github.com/nilsteampassnet/TeamPass.git
2. Go through the install
3. Try to login as admin

### Expected behaviour
Should be able to login

### Actual behaviour
Login credentials incorrect!

### Server configuration
Ubuntu 14.04.5

Server version: Apache/2.4.7 (Ubuntu)

mysql  Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3

PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58) 

latest from GIT

### Client configuration
Any Browser

Windows 10

#### Web server error log

Nothing in error logs

I picked a simple admin password to make sure no funky characters, so its 12345
Installation went fine no complaints, went to login in with the user admin and the password i put in during on any browser and simply say wrong credentials

I read other posts and check teampass_users in mysql, there is nothing in it
I then did;

 INSERT INTO `teampass_users` (`id`, `login`, `pw`, `groupes_visibles`, `derniers`, `key_tempo`, `last_pw_change`, `last_pw`, `admin`, `fonction_id`, `groupes_interdits`, `last_connexion`, `gestionnaire`, `email`, `favourites`, `latest_items`, `personal_folder`) VALUES ('1', 'admin', 'afakepassword', '', '', '', '', '', '1', '', '', '', '0', '', '', '', '0');

now there is something in teampass_users;

+----+-------+---------------+------------------+----------+-----------+----------------+---------+-------+-------------+-------------------+----------------+--------------+-------+------------+--------------+-----------------+----------+-----------------+------------------------+-----------+-----------+---------------+------+----------+-------------+-----------------------+------+------+-------------------+--------+--------------+----------------+------------------+----------------------+--------------+------------------+---------------+---------+
| id | login | pw            | groupes_visibles | derniers | key_tempo | last_pw_change | last_pw | admin | fonction_id | groupes_interdits | last_connexion | gestionnaire | email | favourites | latest_items | personal_folder | disabled | no_bad_attempts | can_create_root_folder | read_only | timestamp | user_language | name | lastname | session_end | isAdministratedByRole | psk  | ga   | ga_temporary_code | avatar | avatar_thumb | upgrade_needed | treeloadstrategy | can_manage_all_users | usertimezone | agses-usercardid | encrypted_psk | user_ip |
+----+-------+---------------+------------------+----------+-----------+----------------+---------+-------+-------------+-------------------+----------------+--------------+-------+------------+--------------+-----------------+----------+-----------------+------------------------+-----------+-----------+---------------+------+----------+-------------+-----------------------+------+------+-------------------+--------+--------------+----------------+------------------+----------------------+--------------+------------------+---------------+---------+
|  1 | admin | afakepassword |                  |          | NULL      |                |         |     1 |             |                   | 1492094911     |            0 |       |            |              |               0 |        0 |               3 |                      0 |         0 | 0         | 0             | NULL | NULL     | NULL        |                     0 | NULL | NULL | none              | NULL   | NULL         |              0 | full             |                    0 | not_defined  | 0                | NULL          | none    |
+----+-------+---------------+------------------+----------+-----------+----------------+---------+-------+-------------+-------------------+----------------+--------------+-------+------------+--------------+-----------------+----------+-----------------+------------------------+-----------+-----------+---------------+------+----------+-------------+-----------------------+------+------+-------------------+--------+--------------+----------------+------------------+----------------------+--------------+------------------+---------------+---------+
1 row in set (0.00 sec)

However i cannot login in with admin and afakepassword

It's pretty irritating....

Thanks

**Comment by codingtez** [comment]
I confirm the same behaviour on a fresh Ubuntu 16.04 install with PHP 7.0.15. Users table is empty, populating it with an admin user account does not resolve the problem.

Really hoping this gets fixed soon.

**Comment by tachijuan** [comment]
And I third this exact behavior on Ubuntu 16.04.2 with PHP 7.0.15

**Comment by Robuch** [comment]
I finded workaround for this issue.
After installation if your users table is still empty go to install  once again:
http://your_ip/teampass/install
And make all steps again, but one of them ends with error.
Dont worry its done. Now you have user in table. 
Go to app url: http://your_ip/teampass/
 And now you can login :)

**Comment by tachijuan** [comment]
@robuch that URL doesn't exist after the install is complete.

**Comment by Robuch** [comment]
Yes, you have right, I skipped this step. That is reason why I could repeat installation. Of course admin cant login if installation directory still exist:)

**Comment by nilsteampassnet** [comment]
After long debug, I identified the issue.
I hope it is solved on your side too.

**Comment by yugigithub** [comment]
no, the problem persist on 2.1.27.3

**Comment by nilsteampassnet** [comment]
Refer to #1769. 
We did a debug session with @ricardoclaus and identified an issue that could be the root  cause of this. 
A commit was pushed including the fix.

**Comment by kumaip** [comment]
I downloaded the last version this morning
but the problem persist
