### ISSUE TITLE
Fresh install, can't log in and no entries in users table.

### ISSUE THREAD

**Issue by gabe31415** [nilsteampassnet/TeamPass#1744]
### Steps to reproduce
1. Install Teampass 2.1.27 on Ubuntu 16.04 TLS 64-bit
note: same exact issues when tried using WAMPSERVER on Windows 10

### Expected behavior
1) "install" directory to be deleted (the install script claims it is gone)
2) should be able to logon as "admin" with password set during install script
3) expect db table "teampass_users" to have an entry for "admin"

### Actual behavior
1) "install" directory still exists
2) can't logon
    2.a) if using Chrome I get "Login credentials do not correspond!"
    2.b) if using Firefox I get the little spinning gear like it's trying to logon BUT it doesn't go anywhere
3) no entries exist in "teampass_users" db table

### Server configuration
**Operating system**:
ubuntu 16.04 TLS 64-bit

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
7

**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**
using chrome and firefox

**Operating system:**
teampass host

#### Web server error log
```
Not sure this matters until an account shows up in the users db table, but mostly I will need to know what logs you want attached since I'm an apache newb.
```

BTW: I've been reading through existing issues and very impressed with the level of responsiveness and help you provide.  Thank you in advance.

**Comment by gabe31415** [comment]
Here is what I have found gets me there, thanks to other comments I found in closed tickets.
1) do the install, try to logon, it fails
2) run the install again by going to http://<localhost>/install/install.php
2.b) run through until you get an error (right before clean up)
3) rename the "install" folder (i renamed to "install.original")
4) logon and it works

note: please don't close since this isn't a proper "fix"

**Comment by nilsteampassnet** [comment]
What package did you install?
A fix was provided in 2.1.27.3

**Comment by gabe31415** [comment]
I pulled it yesterday it shows 2.1.27.
I don't know how to tell the subversion.. please advise.

BTW: loving this!  got 2fa setup and working. can't wait to share my beta setup with the team!

**Comment by nilsteampassnet** [comment]
Please ensure you used https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.27.3

**Comment by netforce** [comment]
same for php5.6, also the install directory is not whiped and can't login. Re-running install works untill the error from at finialization "At least one task has failed! Please correct and relaunch." but all tasks are checked green. Apache errorlog shows nothing of interest in debug mode, access logs show the last file called is /install/install.queries.php

**Webserver** Apache/2.4.25 (Ubuntu) mod_fcgid/2.3.9 mpm-itk/2.4.6-01 PHP/5.5.9-1ubuntu4.21 OpenSSL/1.0.2k
**mysql**  Ver 14.14 Distrib 5.5.55, for debian-linux-gnu (x86_64) using readline 6.3
**teampass**  2.1.27.3 fresh install
**OS**Ubuntu 14.04.5 LTS
**Browser**: to many :)

**Comment by nilsteampassnet** [comment]
Can you provide the log from Firebug or Browser console?

**Comment by kumaip** [comment]
Seem problem,
can't  do nothing

**Comment by nilsteampassnet** [comment]
Did you download package from https://github.com/nilsteampassnet/TeamPass/archive/master.zip ?

**Comment by nilsteampassnet** [comment]
Any news?

**Comment by kumaip** [comment]
yes last version dowloaded. I think I will find another password management solution.
Thanks all the same

**Comment by hackstrip** [comment]
I have the same problem. I did fresh git clone https://github.com/nilsteampassnet/TeamPass
browser <==https==> haproxy <--http-->lighttpd /teampass/
Just realized that the https reverse proxy setup is generating http:// links in the csrfconfig.php
It first it was a http+https problem (install in http this gets csrf fixed url in csrfconfig.php) once in https, hsts prevents the loading of the CSRF javascript. 
Fixed the static http to https links, but still not working. 
Then a new install, now only in https. still same problem

Doing a revisit in the install folder starts the installation new and the JSON response (not visible in browser gui) that you need to manually rename csrfp.config.php. Did that, install completes again, still cannot login the JSON response.

The console shows only some css

Postdata
type=identify_user
tst=1
data=OwOdYeKVLlltj2DZ/YCyKQg3dm1Ina3aCyXXSHeb1dbXLwsY7fDNEGlcOD8A2EYptEAv7rGPvgiGAJXV1BVhgQE2O+VOvARbnFPM6xoNGvcjEjfoev4eqXI7TxRRuJ2dQ+4gvoOjNTUYDMA9+MGPFS+SMGPYg68CZCwhykGdpAG8/AFE1czK2JmgFI+OeLs=
64a55b2c9a62a848b04b62cc910eeeffaf865effc6a7aa26e8=620009a731a1cd62ce8caa99555db5af7bd4f0240ae396b0f5
Response
[{"value" : "user_not_exists", "text":""}]
![123](https://cloud.githubusercontent.com/assets/19146749/26627442/cf374242-45fa-11e7-87b3-bc39f06c8120.png)

**Comment by nilsteampassnet** [comment]
Can you share your screen with me?

**Comment by nilsteampassnet** [comment]
Any news?

**Comment by hackstrip** [comment]
Hi, 

My issue was patched in the latest release (see remark "no admin
created") 

git clone <new> 

drop database teampass; 

rm -rf /secret/teampass/* 

This solved my issue. 

After install all was created, but had to remove install folder myself. 

When looking into the issue (and my commnent) I could not find it
anymore, so assumed case closed.

On 2017-06-15 22:30, Nils Laumaillé wrote:

> Any news? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/nilsteampassnet/TeamPass/issues/1744#issuecomment-308857342
[2]

**Comment by dnormant** [comment]
Installed teampass 2.1.27.3
Centos 7
PHP 5.6
Apache 2.4.6
mysql 5.6.37

Still not able to log in and the script isn't deleting the install directory. I tried gabe31415's trick and it got me going. It took a couple tries - or click "launch" again after the unidentified failure. It looks usable for now but I'll keep checking back. Thanks for you good work.

**Comment by KB7777** [comment]
Hello.
@gabe31415 Thnx for sharing the tip. It works fine.

Bug is still present at 2.1.27.7:
CentOS Linux release 7.3.1611 (Core) (full update)
PHP 7.1.8 (cli) (built: Aug  2 2017 12:13:05) ( NTS ) from remi repo
httpd.x86_64 2.4.6-45.el7.centos.4
MariaDB 10.2.7

Regards.
