### ISSUE TITLE
(After) Authentication problem

### ISSUE THREAD

**Issue by N3RG4L** [nilsteampassnet/TeamPass#1989]
### Steps to reproduce
1. Upgrade from 2.26.13 => 2.27.9
2. Login as admin
3. Go to index.php?page=items  or any page

### Expected behaviour
Items should be displayed, or parameters if you click settings

### Actual behaviour
The gear keep rotating, and nothing happens, until you go manually to a url (index.php?page=items for example) then you get the error message "You are not allowed to see this page." and when you try to click something else on the top menu (settings...) I get disconnected and redirected to login page.
And when going to personal info, I get "Hacking attempt..." message, then the same thing I get disconnected.

### Server configuration
**Operating system**:  Ubuntu 16.04 (phusion/baseimage   docker)

**Web server:** :  Apache 2.4.18 (Ubuntu)

**Database:** : MySQL 5.6.35

**PHP version:** : PHP 7.0.22-0ubuntu0.16.04.1

**Teampass version:** : 2.27.9

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** : Updated from 2.26.13
PLEASE attach to this message the file `/includes/config/tp.config.php`.

global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/teampass/www',
    'cpassman_url' => 'https://teampass.companyname.net',
    'favicon' => 'https://teampass.companyname.net/favicon.ico',
    'path_to_upload_folder' => '/teampass/www/upload',
    'url_to_upload_folder' => 'https://teampass.companyname.net/upload',
    'path_to_files_folder' => '/teampass/www/files',
    'url_to_files_folder' => 'https://teampass.companyname.net/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => '0',
    'ldap_suffix' => '@sampl.ch',
    'ldap_domain_dn' => 'DC=sampl,DC=ch',
    'ldap_domain_controler' => getenv('LDAP_SERVER'),
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '1',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtpinternal.companyname.net',
    'email_smtp_auth' => 'false',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => 'none',
    'email_server_url' => 'https://teampass.companyname.net',
    'email_from' => 'noreply@companyname.net',
    'email_from_name' => 'NoReply',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/teampass/www/backups',
    'bck_script_filename' => 'bck_cpassman',
    'settings_offline_mode' => '1',
    'copy_to_clipboard_small_icons' => '1',
    'timezone' => 'Europe/Paris',
    'saltkey_ante_2127' => 'DSu9XWVmTexBjncZ',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'teampass_version' => '2.1.27',
    'migration_to_2127' => '0',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;st',
	'send_stats_time' => '1506605131',
    'agses_authentication_enabled' => '0',
    'otv_is_enabled' => '0',
    );

### Client configuration
**Browser:** : Chrome  61.0.3163.100

**Operating system:** : Windows 10

#### Web server error log
``` No errors
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
Mixed Content: The page at 'https://teampass.teamwork.net/index.php' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ip-api.com/json'. This request has been blocked; the content must be served over HTTPS.

(I've tried with another https api : https://ipapi.co bypassed the error, but the main problem persist)

Thank you for your help.

**Comment by Hellnino18** [comment]
Hi,

I have the same problem here... Nothing show in log files from Nginx. Same from 2.1.26 to 2.1.27.9

**Comment by Hellnino18** [comment]
When I use Network tab in developer tools from chrome I see that it stays on identify.php (pending status) : 

![image](https://user-images.githubusercontent.com/14218330/32180287-d15a1e32-bd91-11e7-8696-da67842f1ac9.png)

**Comment by N3RG4L** [comment]
Are you trying to connect with admin or another user ?
I had that problem when I try to connect with an LDAP user (identify.php pending) but it was because of my LDAP that was wrong on the database.

**Comment by Hellnino18** [comment]
I have the same problem with admin and LDAP user (gear keep rotating, and nothing happen)

**Comment by nilsteampassnet** [comment]
In /sources/identify.php
change $debugLdap = 0; to $debugLdap = 1;
Then try to log.
Copy the content of file /files/duo.debug.txt

**Comment by Hellnino18** [comment]
This is the content of my ldap.debug.txt : 

`Get all LDAP params :
mode : 1
type : windows
base_dn : dc=mydomain,dc=net
search_base :
bind_dn :
bind_passwd :
user_attribute : 0
account_suffix : @mydomain.net
domain_controllers : mydomain.net
port :
use_ssl : 0
use_tls : 0
*********

Get all ldap params :
base_dn : dc=mydomain,dc=net
account_suffix : @mydomain.net
domain_controllers : mydomain.net
port :
use_ssl : 0
use_tls : 0
*********

Create new adldap object : Success`

After about 3-4min I get : "ldap status : 1" but I'm not connected.

Even with admin user, it seems that it tries to connect with LDAP. Trace : 

`Get all LDAP params :
mode : 1
type : windows
base_dn : dc=mipih,dc=net
search_base :
bind_dn :
bind_passwd :
user_attribute : 0
account_suffix : @mipih.net
domain_controllers : mipih.net
port :
use_ssl : 0
use_tls : 0
*********
`

**Comment by N3RG4L** [comment]
Hi,
Bellow the output of **duo.debug.txt**  : 

Content of data sent 'zAL69gM2+FkzCp1RLmYWfWLUAkTy4oO27w9U5Fow/06FLOUeLRuEwfmX4fzxLAEUkFfM4FRu47AD0ASdQhjudfL3rhFUwxkk4pMKrGUSKygeMWh2sep5ehbMk+ohG8kt5eF4v47didtn9wIEwMOpIZYdT9U9069uU8MMHB/BW4SBquOn2bPb7skkTnmzf2JWw/Rx0UKtwn2XMOkLpvp36xS2OuEc'
Starting authentication of 'admin'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 1
User's token: Maigieguiboohee3oShohphee3beitoeka6yahcahThuejoon3


======================================
and **ldap.debug.txt**   : 

Get all ldap params :
base_dn : DC=company,DC=ch
account_suffix : @company.ch
domain_controllers : company_active_directory
port :
use_ssl : 0
use_tls : 0
*********

Create new adldap object : Success


After authenticate : Success


ldap status : 1

**Comment by nilsteampassnet** [comment]
Strange, user is successfully authenticated in LDAP.
Could you share the answer from the server on identify.php file.
Use your browser console / network / answer to get it.

You may also have errors stored in DB that would be interessant to watch.
Run mysql query : ```SELECT date, label FROM `teampass_log_system` WHERE `type` = "error" order by date DESC```
Perform an export of this and attach it here

Thanks

**Comment by N3RG4L** [comment]
I got this answer from identify.php
"Yf/5WTMzMzNaYTExSljp/3D069EqQ13/3CtLFF3VN3CpHe82veNOUoF4Ky58VD6bBHP2jeixVhy6YcTkdYMmXYAfYYXX99mgf/TCxiJMYpVJ5HJpRs+jyiw8FqlOb9LLStGay/bsMsnDfA=="

And on the database I have this : 

Query: UPDATE `teampass_users` SET `key_tempo`='OuX9ahch1SaicooTh6oophil9ur0yoo0rongai1eeboo1eiwoi', `last_connexion`=1509556065, `timestamp`=1509556065, `disabled`=0, `no_bad_attempts`=0, `session_end`=1509559665, `psk`='', `user_ip`='' WHERE id=1<br />Error: Unknown column 'user_ip' in 'field list'<br />@ /sources/identify.php

Thank you Nils for your help

**Comment by nilsteampassnet** [comment]
You are welcome.

Did you run the upgrade process?
It seems a field is missing in your database. This field was recently introduced and requires to be added.
Can you run http://xxxxxx/teampass/install/upgrade.php

**Comment by Hellnino18** [comment]
Hi nils, I have exactly the same problem. And I perform the upgrade process withtout any problem from 2.1.26. Mine is a little weird, because of the field passed in the user_ip column : 

`UPDATE `teampass_users` SET `key_tempo`='cohDo0mae2aiM3shahCheekaithabei5gieDaekeivae5Eedoh', `last_connexion`=1509448524, `timestamp`=1509448524, `disabled`=0, `no_bad_attempts`=0, `session_end`=1509452124, `psk`='', `user_ip`='FR-Toulouse-Europe/Paris' WHERE id=50<br />Error: Unknown column 'user_ip' in 'field list'<br />@ /sources/identify.php`

Thanks.

**Comment by N3RG4L** [comment]
Hi Nils,

Yes I did upgrade, and it was with no error (except curl php extension that was not enabled, but I think that it doesn't cause any problem).

Which field is missing ? if it's the user_ip I think it's because of the ip-api.com that is not compatible with https (got mixed content error) #1970   (I saw your last commit on that issue, waiting for your confirmation to apply it)

best regards,

**Comment by nilsteampassnet** [comment]
This is really strange.
Can you confirm that this field is not in your table `users`?

In upgrade script for 2.1.27, the next code is written.
````
// alter table USERS to add a new field "user_ip"
$result = mysqli_query("SHOW COLUMNS FROM `users` LIKE 'user_ip'");
if (mysqli_num_rows($result) !== 0) {
    // Change name of field
    mysqli_query($db_link, "ALTER TABLE `".$pre."users` CHANGE `user_ip` `user_ip` VARCHAR(400) NOT NULL DEFAULT 'none'");
} else {
    // alter table misc to add an index
    $res = addColumnIfNotExist(
        $pre."users",
        "user_ip",
        "VARCHAR(400) NOT NULL DEFAULT 'none'"
    );
}
```

**Comment by N3RG4L** [comment]
No there is no column named "user_ip" on my **$pre."users"** table
Should I add that column ?

**Comment by Hellnino18** [comment]
Nils,

Your verification is made on "users" not on ".$pre."users", mysql return an error because table users doesn't exist. Maybe this is the mistake here ?

**Comment by N3RG4L** [comment]
Hellnino18 the column should be on your users table means prefix_users (for example my table is teampass_users) try to add the column.

**Comment by Hellnino18** [comment]
@N3RG4L I know that :) I said that to Nils because of this line  : 

// alter table USERS to add a new field "user_ip"
$result = mysqli_query("SHOW COLUMNS FROM `users` LIKE 'user_ip'");

I think it should be : 

$result = mysqli_query("SHOW COLUMNS FROM `".$pre."users` LIKE 'user_ip'");

Because at this moment, the query fails.

**Comment by N3RG4L** [comment]
My bad, didn't read well. I think you are right. and mysqli_query should return an exception (which is !== 0)

**Comment by nilsteampassnet** [comment]
Yes you are right.
I did a bad copy-paste here, and it's a bug.
I'm committing a fix.

**Comment by Hellnino18** [comment]
Hi Nils, thanks for your return. I tried your fix but it doesn't work on my side, always no column user_ip. I see another bad copy/paste : line 192 : 
```
// alter table MISC - rename ID is exists
$result = mysqli_query("SHOW COLUMNS FROM `misc` LIKE 'id'");
```

**Comment by Hellnino18** [comment]
I have changed the line for the table MISC for : 

$result = mysqli_query("SHOW COLUMNS FROM `".$pre."misc` LIKE 'id'");

But I have always a problem, the new column is not added to the users table.

**Comment by nilsteampassnet** [comment]
You must have errors in the apache logs.
Would it be possible to share it?

**Comment by Hellnino18** [comment]
@nilsteampassnet There is no error in Nginx logs. File is empty.

> Upper you write

$result = mysqli_query("SHOW COLUMNS FROM ".$pre."users LIKE 'user_ip'");

Because at this moment, the query fails.
What do you mean by this the query fails? when you run the query in mysql for example?

Since you change this line ($result = mysqli_query("SHOW COLUMNS FROM ".$pre."users LIKE 'user_ip'");) there is no problem. You just need to do the same on thi request : 

$result = mysqli_query("SHOW COLUMNS FROM ".$pre."misc LIKE 'id'");

**Comment by nilsteampassnet** [comment]
It has been done

**Comment by Hellnino18** [comment]
@nilsteampassnet : if you haven't change anything else that the 2 requests, it doesn't work on my side. @N3RG4L : do you still have the problem ?

**Comment by N3RG4L** [comment]
@Hellnino18 No my problem was solved just by adding only the "user_ip" column.

**Comment by Hellnino18** [comment]
@N3RG4L : you add it by hand ? Or you just play another time the upgrade script ?

**Comment by N3RG4L** [comment]
Yes I've added it directly to the database, without rerunning the upgrade script.

**Comment by Hellnino18** [comment]
Thanks for your feedback. So the problem is still there, from a 2.1.26 version. So I'm waiting a fix.
