### ISSUE TITLE
New created folders cannot be seen

### ISSUE THREAD

**Issue by sfrlaurent** [nilsteampassnet/TeamPass#2420]
when a user creates a new folder, the folder is created in "no access" for everybody.
Whats the way for the user to make it readable or writable by some roles ?

**Comment by nilsteampassnet** [comment]
Please use the form for ticket description

**Comment by sfrlaurent** [comment]
OK that is :
### Steps to reproduce
1. logon on teampass with a user who is manager of a role
2. create a new folder
3. go to "manage role" tab and the new folder is not there. Noone except the admin is able to see it.

### Expected behaviour
in the previous version it was accessible by the users included in the role the manager is managing. 
The  users members of other roles are not able to read this folder (and its content)

### Actual behaviour
only the admin (global admin of all the application) can access and modify the folder access list

### Server configuration
ubuntu 16.04

**Web server:**
apache/2.4.18
**Database:**
mysql 14.14

**PHP version:**
php 7.0.30

**Teampass version:** 
2.1.27.22

**Teampass configuration file:**

**Updated from 
2.1.27.7
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
firefox or chrome
**Operating system:**
windows7
### Logs
no logs

**Comment by sfrlaurent** [comment]
OK . I understood  the trouble.
When the option " New sub-folders inherit permissions from parent folder  " is off, the permissions on a new folder is not the users's permission but noaccess for everyone.
in the 2.1.27.7 version if the option was off , the behaviour was to inherit from parent (the same as expected if the option was on)

**Comment by nilsteampassnet** [comment]
Thank you for this analysis
Indeed the old feature was implemented in the wrong direction. Now it is corrected

**Comment by alarido** [comment]
I don't see where or how it's solved maybe I am not doing something correctly.

I tried to upgrade to 2.1.27.23 and enable or disable new folder inherit permisions of root folder on folder creation.

Problem persists, a user creates a folder during creation user gets a JSON error, folder cannot be seen by the user, but once you login as administrator you can see the folder has been created without any permissions.
