### ISSUE TITLE
[3.0.0.2] LDAP is not working

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2831]
### Steps to reproduce
1.Login to Admin
2. Try to setup LDAP

### Expected behaviour 
Setting saves

### Actual behavior
After page refresh or page changing, setting are not saved. 
Also is there all fields? On v2.7 there is field "LDAP domain controller(s)" where we specify LDAP servers.

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.2

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 20H2

**Comment by nilsteampassnet** [comment]
Has fixed the issue regarding selection not saved.
I didn't test yet the ability to log through LDAP but it should work.

**Comment by reginfo** [comment]
I will try it, but I need to test in production environment. I will let you know.

**Comment by reginfo** [comment]
So I`ve tested LDAP. 
So What I have discovered.
When you open LDAP settings, I see this picture:
![LDAP Err](https://user-images.githubusercontent.com/4628571/98835947-c0282100-2449-11eb-98c8-a649cd2452e4.PNG)
So I enable LDAP authentication and select Windows/Active directory. 
I could not see where to enter LDAP domain controllers IP.
![LDAP Err 1](https://user-images.githubusercontent.com/4628571/98836279-2c0a8980-244a-11eb-9ede-8033db6d46e6.PNG)
So if I jump to another page and then back, LDAP search base field replaces:
![LDAP Err 2](https://user-images.githubusercontent.com/4628571/98836381-4b091b80-244a-11eb-9384-8b7789ba2076.PNG)

So everything is set (settings like on 2.7.x version).
Trying to test and It`s not working. 
In Progress pop-up ring spinning and in console I get an error:
![LDAP Err 3](https://user-images.githubusercontent.com/4628571/98836666-a0452d00-244a-11eb-841d-203e7561cfc8.PNG)
```
index.php?page=ldap:1980 ldap-test-config
jquery.min.js:2 POST http://192.168.xx.xx/teampass/sources/ldap.queries.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
S.<computed> @ jquery.min.js:2
(anonymous) @ index.php?page=ldap:1990
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

Also some errors in appache2 error log:
```
[Wed Nov 11 18:23:10.292596 2020] [php7:notice] [pid 27156] [client 192.168.xx.xx:1368] PHP Notice:  Undefined index: ldap_ssl_input in /var/www/html/teampass/sources/ldap.queries.php on line 224, referer: http://192.168.xx.xx/teampass/index.php?page=ldap
[Wed Nov 11 18:23:10.302868 2020] [php7:notice] [pid 27156] [client 192.168.xx.xx:1368] PHP Notice:  Undefined index: ldap_ssl_input in /var/www/html/teampass/sources/ldap.queries.php on line 242, referer: http://192.168.xx.xx/teampass/index.php?page=ldap
[Wed Nov 11 18:23:10.304469 2020] [php7:notice] [pid 27156] [client 192.168.xx.xx:1368] PHP Notice:  Undefined index: username_pwd in /var/www/html/teampass/sources/ldap.queries.php on line 257, referer: http://192.168.xx.xx/teampass/index.php?page=ldap
[Wed Nov 11 18:23:10.304591 2020] [php7:error] [pid 27156] [client 192.168.xx.xx:1368] PHP Fatal error:  Uncaught Error: Class 'voku\\helper\\UTF8' not found in /var/www/html/teampass/includes/libraries/voku/helper/AntiXSS.php:588\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/voku/helper/AntiXSS.php(1766): voku\\helper\\AntiXSS->_do('Get all ldap pa...')\n#1 /var/www/html/teampass/sources/ldap.queries.php(270): voku\\helper\\AntiXSS->xss_clean('Get all ldap pa...')\n#2 {main}\n  thrown in /var/www/html/teampass/includes/libraries/voku/helper/AntiXSS.php on line 588, referer: http://192.168.xx.xx/teampass/index.php?page=ldap
```

**Comment by Domekologe** [comment]
Hi,

we are facing the same issue.
Is there a possibility to enable the Debug Mode?
The old way, which is provided in Documentation, is not working.

Thank you

**Comment by Domekologe** [comment]
Hello,
after the update you provide, I am able to see the "Output"
![image](https://user-images.githubusercontent.com/40795176/99044299-d809bd00-258f-11eb-8129-f3e2c7ff8fcc.png)

I also tried it with Port 389 and without SSL/TLS (which will be disabled in a few weeks in the environment).
I also tried it with a wrong password, to see if the user will be locked out, but nothing happens.

If you need more information, logs, or something else, please tell me

**Comment by reginfo** [comment]
I have the same error
```
ldap status : Not possible to get connected with this user
```

**Comment by nilsteampassnet** [comment]
I decided to switch to a standard PHP library.
I'm currently implementing [ldaprecord](https://github.com/DirectoryTree/LdapRecord).
Facing some illogical issues but I'm wondering if it is related to my quick and dirty ldap server I have on my synology.

**Comment by reginfo** [comment]
> Finally understood how it works ... so work in progress ;)

Great news.

**Comment by dmotelica** [comment]
> 
> 
> > Finally understood how it works ... so work in progress ;)
> 
> Great news.

Hello, 
you should modify your files as follows:

--------------------------------------------------
file /sources/ldap.queries.php :

line 127: 
         if (strpos(html_entity_decode($dataReceived['username']), '\\') === true) {
  
with :
         if (strpos(html_entity_decode($dataReceived['username']), '\\') == true) {

line 144 :
        if ($SETTINGS['ldap_ssl']) {
with :
        if ($SETTINGS['ldap_tls']) {


line 224,225:
               '  - use_ssl : ' . $SETTINGS['ldap_ssl_input'] . '<br/>' .
                '  - use_tls : ' . $SETTINGS['ldap_ssl'] . '<br/>*********<br/>';

with:
               '  - use_ssl : ' . $SETTINGS['ldap_ssl'] . '<br/>' .
                '  - use_tls : ' . $SETTINGS['ldap_tls'] . '<br/>*********<br/>';

line 242, 243:
                'use_ssl' => $SETTINGS['ldap_ssl_input'],
                'use_tls' => $SETTINGS['ldap_ssl'],

with:
                 'use_ssl' => $SETTINGS['ldap_ssl'], 
                    'use_tls' => $SETTINGS['ldap_tls'], 

------------------------------------------------------------------------------
in file /pages/ldap.php:

line 207:
       <div class='row mb-2 tr-ldap tr-posix-search<?php echo (isset($ldap_type) === true && $ldap_type === 'windows') ? '' : ' hidden'; ?>'>

with: 
      <div class='row mb-2 tr-ldap tr-windows<?php echo (isset($ldap_type) === true && $ldap_type === 'windows') ? '' : ' hidden'; ?>'>


line 219: 
         <div class='row mb-2 tr-ldap tr-posix-search<?php echo (isset($ldap_type) === true && $ldap_type === 'windows') ? '' : ' hidden'; ?>'>

with: 
         <div class='row mb-2 tr-ldap tr-windows<?php echo (isset($ldap_type) === true && $ldap_type === 'windows') ? '' : ' hidden'; ?>'>


After that, your bug with LDAP page would be fixed and LDAP Test connection should work. 
But if you use LDAP type Windows, you should not be able to login with a domain user. Nils has to work on it.

**Comment by Domekologe** [comment]
In my case it is a WIndows Active Directory Authentication which we are using.

**Comment by nilsteampassnet** [comment]
I have implemented LDAPRecord library.
As a first step, I have implemented it this way.

Users existing in AD must be synchronized by an admin inside Teampass.
Once this is done, the AD user will be able to log inside Teampass using his AD password.

Remember now that the user authentication password is used to encrypt his private key (as explained in next picture)
![teampass3_necryption_model](https://user-images.githubusercontent.com/1197546/99910718-e2465c80-2cef-11eb-8b73-4fc88093eb19.png)

That means that if user changes his password in AD, then he will have to provide his previous password to decrypt the private key. It will then be encrypted with the current password.

**Comment by reginfo** [comment]
Tried latest build. 
Could not get it to work. 
I`m getting :
```
Caution
Error : -1 - Can't contact LDAP server
```

```
[Sun Nov 22 20:31:11.791593 2020] [php7:notice] [pid 99723] [client 192.168.xx.xx:1873] PHP Notice:  Undefined index: ldap_bind_passwd in /var/www/html/teampass/sources/ldap.queries.php on line 125, referer: http://192.168.xx.xx/teampass/index.php?page=ldap
```
No errors in Console

Settings:
![2020-11-22_20h35_38](https://user-images.githubusercontent.com/4628571/99913895-d912bb00-2d02-11eb-814b-d1a7d2ebc412.png)

**Comment by nilsteampassnet** [comment]
Found the reason of your message. I did change some parameters name and mixed them up in the code.
Also here is how I have set it up in my case
![image](https://user-images.githubusercontent.com/1197546/99934498-70f1c280-2d5e-11eb-9810-cbeae6854e2e.png)

**Comment by whositwhatnow** [comment]
Ive updated my instance and its still not working for me.  I am using Active directory for login:
![tpsetting](https://user-images.githubusercontent.com/22056604/99988443-a2c75100-2d7f-11eb-8b8d-e37529bf1cbe.jpg)

**Comment by whositwhatnow** [comment]
Undefined index: ldap_bind_passwd in /var/www/html/sources/users.queries.php on line 2285

**Comment by reginfo** [comment]
Yep, tried also, Not working. The same error
```
Caution
Error : -1 - Can't contact LDAP server
```

**Comment by dmotelica** [comment]
> 
> 
> Undefined index: ldap_bind_passwd in /var/www/html/sources/users.queries.php on line 2285


That's because the variable "ldap_bind_passwd" is used file in /var/www/html/sources/users.queries.php on line 2285. But in config tp.config.file and DB table _misc there is anothr varibale used: "ldap_password". 

I have checked and found out that the variable "ldap_bind_passwd" is used in other php files...
So now I'm trying to change all this uncorrected errors.

**Comment by dmotelica** [comment]
> 
> 
> I have implemented LDAPRecord library.
> As a first step, I have implemented it this way.
> 
> Users existing in AD must be synchronized by an admin inside Teampass.
> Once this is done, the AD user will be able to log inside Teampass using his AD password.
> 
> Remember now that the user authentication password is used to encrypt his private key (as explained in next picture)
> ![teampass3_necryption_model](https://user-images.githubusercontent.com/1197546/99910718-e2465c80-2cef-11eb-8b73-4fc88093eb19.png)
> 
> That means that if user changes his password in AD, then he will have to provide his previous password to decrypt the private key. It will then be encrypted with the current password.


Hello Nils,

The desired mode to configure LDAP in TeamPass would be "Windows/ActiveDirectory" mode because there is no username and password stored in clear in tp.config.php file. 

The other options you try to add like Posix-Search or OpenLDAP stores "ldap_bind_password" in clear which is not securely. 

Thank you.

**Comment by nilsteampassnet** [comment]
I have pushed a fix for those variables name change.

Also you may look at the documentation of the used library to see how to set up the ldap configuration
https://ldaprecord.com/docs/core/v2/configuration/

**Comment by reginfo** [comment]
Tried multiple variations of settings. Didn`t get it to work.

**Comment by dmotelica** [comment]
Tried also..... LDAP test Config : Result "Great", but when trying to authenticate with an AD user, I have "Login credentials do not correspond" message.

**Comment by reginfo** [comment]
@dmotelica , are you using AD or another LDAP? 
What setting are you using to get LDAP test - Result Great?

**Comment by dmotelica** [comment]
> 
> 
> @dmotelica , are you using AD or another LDAP?
> What setting are you using to get LDAP test - Result Great?


I'm using ActiveDirectory. I made some modifications to /sources/ldap.queries.php, /sources/users.queries.php, /pages/ldap.php to have the result GREAT. And this was only if using LDAP:389. It doesn't work using LDAPS:636

As I wrote in a previous comment to Nils, I would like to use "Windows/ActiveDirectory" and adLDAP library because the config file doesn't store the credentials at all. 
Using LDAPRecord needs credentials to search in AD, and these credentials are saved in the config file in clear mode.

**Comment by dmotelica** [comment]
I found why LDAP authentication does not work for all of us: 

file identify.php:

function authenticateThroughAD($username, $userInfo, $passwordClear, $SETTINGS)
{
    // Build ldap configuration array
    $config = [
        // Mandatory Configuration Options
        'hosts'            => [$SETTINGS['ldap_domain_controler']],
        'base_dn'          => $SETTINGS['ldap_search_base'],
_**'username'         => $SETTINGS['ldap_user_attribute']."=".$username.",cn=users,".$SETTINGS['ldap_bdn'],**_
        'password'         => $passwordClear,


the  "username" is hardcoded with "cn=users" wich is not the case for my AD.

**Comment by nilsteampassnet** [comment]
Oops yes you are right, I missed this one.
I have added a new field called `Distinguished Names suffix (if needed)`. Is this enough precise?

**Comment by tiredofit** [comment]
Instead of username it should actually be a distinguished name field.
For example:

DSA (Read Only Accounts) typically look like this cn=readonlyadccount,ou=whatever,dc=your,dc=org
User Accounts typically look like this uid=username,ou=probablysomethingdifferent,dc=your,dc=org

In most environments it is referenced as the "Bind DN"

**Comment by nilsteampassnet** [comment]
@tiredofit 
OK so according to you, field called `username` should be renamed `Bind DN`, correct?

**Comment by nilsteampassnet** [comment]
Here is the setting form.
![image](https://user-images.githubusercontent.com/1197546/100521128-0a2b3980-31a2-11eb-909c-f2f82504bde1.png)
It is inspired from [JIRA documentation](https://confluence.atlassian.com/adminjiraserver/connecting-to-an-internal-directory-with-ldap-authentication-938847055.html)

**Comment by tiredofit** [comment]
OK I see how that can be confusing. If you wanted to keep the "username" field it would be helpful to leave an example on the screen as many users would get confused wondering if they just need to put in a username, a distinguished name. Where it gets interesting is that since you have a Username attribute already of uid this could also add to their confusion for that field.

I'm not entirely sure the use personally of the additional user DN option, it would be typically handled via the baseDN.
What _would_ be very useful is to allow the use of filters. With a filter one could only allow specific users to connect based on their group membership or by matching an attribute. Here's a very basic example:

`(&(memberOf=CN=app-teampass,OU=groups,OU=Access,DC=example,DC=org)(!(disabled=TRUE)))`

That is a combination filter that only allows users to login if they have a group membership to `app-teampass` _AND_ they don't have the attribute of `disabled=TRUE` set.

**Comment by tiredofit** [comment]
Sorry to add to this - if you are using LDAP Record (successor to ADLDAP2 - cool!) you have some real benefits of being able to auto populate some fields. If you were to have a few fields for a users First Name (typically givenName), Last Name (typically sn) you could autopopulate some of those values. Also, auto populating their mail address (typically mail, but should be customizable). You could even take it a step further and query their Groups! Then you could create sections in Teampass that were only visisble to users that were members of the group essentially auto provisioning the users to the correct sections.

Last but not least, was a feature that was in your 2.x branch which would be very beneficial as well and is part of the LdapRecord package I believe, is the inclusion of being able to automatically login using servers headers. BY passing $_SERVER_REMOTE_USER or something configured by the admin this would allow someone already logged into an enterprise authentication system to login to Teampass. Commonjly known as Windows Authentication, but there are other words for it as well. Often it is written about as `AUTH_USER` `REMOTE_USER` `REMOTE_PASSWORD` etc.

Hope this helps ;)

**Comment by dmotelica** [comment]
I also found that since v3 there is no sk.php file, only secret-key txt file. Is that OK?

**Comment by nilsteampassnet** [comment]
@tiredofit 
Thank you for your explanations.
Regarding the possibility to use such filters with ldapRecord, it seems not possible. It needs to be decompossed.
What criteria are expected? I believe `allowed groups`, `locked`, `disable`, `orgnizational units`
Do you see some other?

@reginfo corrected

@dmotelica yes it is

**Comment by reginfo** [comment]
Really can get it connected to our AD server. =(

**Comment by nicolass67** [comment]
Hi all, 

I'm facing the same issue to get Teampass to work with LDAP. 
I use a fresh Debian 10 + LAMP Stack (PHP 7.3). 
Teampass is 3.0.0.7 fresh install too. 

My LDAP server is based on OpenLDAP . It's working I can do ldapsearch and so commands sucessfully. 

I tried to debug by setting : 
DEBUGLDAP to true in the file <root of teampass>/includes/config/include.php.
It generates a logfile in files/ldap.debug.txt ... but this file is empty. 
Anyway to make it more verbose ? 

Regards,

**Comment by gruffatremi** [comment]
Hello, 
I have freshly installed 3.0.0.7 with php 7.4 and apache2.4.41 and I am facing the same issues "Error : -1 - Can't contact LDAP server" 
Trying with a Windows AD which is working for sure. I also don't have files folder when I unzipped the tar.gz hence I can't find the ldap.debug.txt. 
Any help appreciated ! 
Regards,

**Comment by jutler** [comment]
Same issue for me, fresh install of 3.0.0.7, php7.  No matter what i try, i keep getting "Error: 1 - Can't contact LDAP server".  Any help would be really appreciated.  Having to work on a deadline to push this out to users.

**Comment by IgorRedaelli** [comment]
I am experiencing the same problem. There is something wrong in LDAP Teampass integration. 
If I enter the port number (389 in my case) Teampass always responds with "Error: 1 - Can't contact LDAP server" and if I leave it empty the port instead responds with an error 500 in the console.

**Comment by NetscalerLover** [comment]
Does anyone solved this issue?. Same Thing here, Error: 1 - Can't contact LDAP server. fresh install of 3.0.0.7. Tried a couple of things but none solved this issue. Its a really cool Product, but without LDAP functionality we cant use it.

**Comment by jtreen** [comment]
I have the same issue on a fresh install. No matter the combination of settings, I get "Error: 1 - Can't contact LDAP server". Ldapsearch with same settings works correctly.

**Comment by rlabellasfr** [comment]
I have the same issue on a fresh install. I get "Error: 1 - Can't contact LDAP server".

**Comment by KOTOXJle6** [comment]
Got the same problem. Version 3.0.0.7 . 
If i write 389 port, i get error "Error: 1 - Can't contact LDAP server".
There is  text "Only insert a port if your LDAP server uses a unique port." - but if i leave it blank, i get another error:

> Fatal error: Uncaught LdapRecord\Configuration\ConfigurationException: Option port must be an integer. in /var/www/teampass/includes/libraries/LdapRecord/Configuration/Validators/IntegerValidator.php:15 Stack trace: #0 /var/www/teampass/includes/libraries/LdapRecord/Configuration/DomainConfiguration.php(176): LdapRecord\Configuration\Validators\IntegerValidator->validate() #1 /var/www/teampass/includes/libraries/LdapRecord/Configuration/DomainConfiguration.php(117): LdapRecord\Configuration\DomainConfiguration->validate('port', '') #2 /var/www/teampass/includes/libraries/LdapRecord/Configuration/DomainConfiguration.php(70): LdapRecord\Configuration\DomainConfiguration->set('port', '') #3 /var/www/teampass/includes/libraries/LdapRecord/Connection.php(68): LdapRecord\Configuration\DomainConfiguration->__construct(Array) #4 /var/www/teampass/sources/ldap.queries.php(150): LdapRecord\Connection->__construct(Array) #5 {main} thrown in /var/www/teampass/includes/libraries/LdapRecord/Configuration/Validators/IntegerValidator.php on line 15

**Comment by dmotelica** [comment]
> Found the reason of your message. I did change some parameters name and mixed them up in the code.
> Also here is how I have set it up in my case
> ![image](https://user-images.githubusercontent.com/1197546/99934498-70f1c280-2d5e-11eb-9810-cbeae6854e2e.png)

@nilsteampassnet :
Don't waste you time to integrate it with LDAP. It would be better to integrate it with Azure AD SSO. You have 2 options: SimpleSAMLphp or php module openidc. using these options, you will have to map the session for the authenticated user. And with Azure AD SSO you will also have the MFA.

**Comment by cciuleanu** [comment]
Hi,

Any updates on this issue?
Regards,
Calin

**Comment by whositwhatnow** [comment]
@cciuleanu I just rolled back to most recent v2 until this is resolved, maybe just do that.

**Comment by cciuleanu** [comment]
> @cciuleanu I just rolled back to most recent v2 until this is resolved, maybe just do that.

I tried also latest v2 version but it  does not work for me either.
Tested 3.0.0.7 and latest v2 on CentOS 7 , 8 and several PHP versions including the lastest 8.0.2

Regards,
Calin

**Comment by TSJasonH** [comment]
> I have implemented LDAPRecord library.
> As a first step, I have implemented it this way.
> 
> Users existing in AD must be synchronized by an admin inside Teampass.
> Once this is done, the AD user will be able to log inside Teampass using his AD password.
> 
> Remember now that the user authentication password is used to encrypt his private key (as explained in next picture)
> ![teampass3_necryption_model](https://user-images.githubusercontent.com/1197546/99910718-e2465c80-2cef-11eb-8b73-4fc88093eb19.png)
> 
> That means that if user changes his password in AD, then he will have to provide his previous password to decrypt the private key. It will then be encrypted with the current password.

Most security-minded AD/LDAP admins force user password changes (expirations) on a schedule. This implementation forcing a user to essentially remember their previous password and change it twice seems cumbersome and prone to data loss since users will inevitably not remember their old passwords.

**Comment by turekg** [comment]
Installed version 3.0.0.7 today on Ubuntu 20.04. The ldap test fails saying that it cannot connect to ldap. Apache log reports:
```
[Mon Mar 08 12:13:11.930853 2021] [php7:notice] [pid 300075] [client 172.16.254.147:51294] PHP Notice:  Undefined index: ldap_username in /data/vhosts/teampass/sources/ldap.queries.php on line 124, referer: https://teampass.mercator-ocean.fr/index.php?page=ldap
[Mon Mar 08 12:13:11.930890 2021] [php7:notice] [pid 300075] [client 172.16.254.147:51294] PHP Notice:  Undefined index: ldap_password in /data/vhosts/teampass/sources/ldap.queries.php on line 125, referer: https://teampass.mercator-ocean.fr/index.php?page=ldap
```
Is there a workaround?
Ta.

**Comment by snumsdisagithub** [comment]
Same problem ("Error: 1 - Can't contact LDAP server") with ldaps port (636) or ldap port (389).
I'm running the last version.

tcpdump don't show a trace to an ldap port while testing the connectivity from the web UI.

With an ldapsearch from the server, that's work fine.

**Comment by Nisfero** [comment]
Hello, discovering the product and facing exactly the same issue on RHEL 8 with v 3.0.0.7; ldapsearch works like a charm but not in the interrface.

I don't know is this can help but i've seen some kind of duplicates in the tp.config.php file about ldap configuration :

On lines 29 > 39 you can find 

`   'ldap_mode' => '0',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'sAMAccountName',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
`

then going to the end of the configuration file you find the values you are currently setting up on the web interface;

`    'ldap_bdn' => 'DC=domain,DC=local',
    'ldap_username' => 'CN=readeraccountusername,OU=accounts,DC=ad,DC=cirb,DC=lan',
    'ldap_password' => 'TheSuperCoolPassword ;)',
    'ldap_new_user_role' => '1',
    'ldap-test-config-username' => 'somedummyuserfortest',
    'ldap-test-config-pwd' => 'blankpassword...',
    'ldap_dn_additional_user_dn' => '',
`

Could there be some kind of conflicts ? I'm absolutely not expert at all in all thos things, just trying to help a bit :)

Steven

**Comment by edgar-koster** [comment]
I just noted something which might help. I was looking into this and started at the first place for me, what is required for the ldap connection with LdapRecord, for reading all posts, this seems to be the case. 

So according to this, you need an array of hosts (https://ldaprecord.com/docs/core/v2/connections/).

I set off to see where my host entries where, found them in `tp.config.php` in setting `ldap_hosts`. Then I seached through the directory for teampass (version 3.0.0.7) for the value and only found two, one language file and one page. That didn't seem right so I search for `ldap_username` which I found more often, for example in `ldap.queries.php`. Immediatly I noticed something. In this file, the hosts is filled by `ldap_domain_controller`. In the config this is set to `0`. 

So what I did, since the file is updated on the fly, change some configurations so I have a valid server. Then I changed the file so `ldap_domain_controler` contained the value of `ldap_hosts` forcing a save since it was overwriten. Then I tested the user. Now instead of a connection error like we all get, I get a message the credentials are incorrect. This is correct in my case for I hadn't set them correctly.

![image](https://user-images.githubusercontent.com/24190040/117026819-63bd0480-acfc-11eb-8020-a1f8c23ba8dd.png)

I'm not sure, but I think if I replace all these `ldap_domain_controller` entries in these files with `ldap_hosts` it might help solving this. (screenshot is windows, but I run teampass on linux)

**Comment by benodilo** [comment]
Hello,
Same problem on 3.0.0.7 ? Don't work on port 389 or 636 with AD.
On the same server that's work fine with older version 2.X
Best regards.

**Comment by turekg** [comment]
> Hello,
> Same problem on 3.0.0.7 ? Don't work on port 389 or 636 with AD.
> On the same server that's work fine with older version 2.X
> Best regards.

It's just hasn't been implemented. If you look at the 3.X branch(s) you will see that the LDAP folder is not there

**Comment by benodilo** [comment]
> 
> 
> > Hello,
> > Same problem on 3.0.0.7 ? Don't work on port 389 or 636 with AD.
> > On the same server that's work fine with older version 2.X
> > Best regards.
> 
> It's just hasn't been implemented. If you look at the 3.X branch(s) you will see that the LDAP folder is not there


ok thks for reply !

**Comment by ckatterl** [comment]
You mean, that LDAP-Authenticatioin is not yet implemented in 3.0.0.7? As per release-info, it should be?
I am too stuck in the "Can't connect-issue"....

**Comment by ckatterl** [comment]
Tried version 3.0.0.8 now. The "can't connect" issue is gone. but the gear is rotating and does not stop. checking with tcpdump, i cannot see any traffic on the ldap-ports.

**Comment by f0ssie** [comment]
I've also tried version 3.0.0.7 today, a completely fresh installation, but I also got the "Error: -1 - Can't contact LDAP server" error message. No matter what I enter in the Hosts field, tcpdump shows that the server always tries to connect to 127.0.0.1:

```
15:42:26.527850 IP 127.0.0.1.52084 > 127.0.0.1.389: Flags [S], seq 2934674681, win 65495, options [mss 65495,sackOK,TS val 2878634823 ecr 0,nop,wscale 7], length 0
15:42:26.527869 IP 127.0.0.1.389 > 127.0.0.1.52084: Flags [R.], seq 0, ack 2934674682, win 0, length 0
```

**Comment by ckatterl** [comment]
The current version 3.0.0.8 produces ldap-queries against the server now (checked with tcpdump). However, using the ldap-test I get an error:

Error : 49 Invalid credentials.
AcceptSecurityContext error, data 52e, v4563.

Normally, this means, that the password isn't correct, but the username is.

I tried to use a username, which does not exist. Then, there's no error message but the circle is rotating saying "in progress". Using a correct username but wrong password immediately throws the above error - same as with correct password.

Any advice?

BR, Christian

**Comment by AtlanteDeveloppement** [comment]
Hello
Same problem with 3.0.0.8 
ldap with active directory doesn't work
Error : 49 Invalid credentials.
AcceptSecurityContext error, data 52e, v4563.
Thanks

**Comment by pablojrc** [comment]
HI!
I have the same situation in a 
CentOS 7.9
PHP 7.4
MariaDB 

![imagen](https://user-images.githubusercontent.com/22251817/136065723-66da5a7d-1e14-4839-8fd9-58513318fc89.png)

**Comment by byalcin23** [comment]
I have a similar issue with TeamPass 3.0.0.8.
![image](https://user-images.githubusercontent.com/71520530/146344116-b885ad13-ad96-4495-8daa-bd4dc07cffae.png)

**Comment by jim-ccit** [comment]
Still broken in 3.0.0.9, exactly the same issues and results as above.

**Comment by sergey2786** [comment]
Version 3.0.17 no connect to ldap(
Error 500 in nginx.
If so, what is the solution to this problem?

**Comment by jvalters** [comment]
The same issue is there any solution?

**Comment by LaiaRos** [comment]
Hello,

Still the same issue with Ubuntu 22.04 and TeamPass 3.0.0.22. Every test remains "In progress" eternally.

Thanks.

**Comment by sfoglema** [comment]
So I went through the process of upgrading from 2.1.26 to 3.0.0.22.
This upgrade already had AD LDAP working and still works on 3.0.0.22.
However, the LDAP screen shows no information that LDAP is setup.
The tp.config.php file does show my LDAP settings.
We do occasionally get the "in progress" issue, but refreshing and logging in again seems to fix it.
Overall, there are several minor issues, but way better than being on LastPass. 
My setup is on CentOS7 (I know, I need to migrate soon), PHP 8 and TeamPass 3.0.0.22

**Comment by jvalters** [comment]
> It now appears that my AD LDAP config is NOT working, but instead your most recent password was simply saved in Teampass. As soon as anyone changes their AD password, they cannot connect to TeamPass unless they use their OLD password.
> 
> 
> 
> Any update on getting LDAP integration working with TeamPass 3.0.0.22?
> 
> 
> 
> Thanks.

We're still waiting for the group filter to be added by @nilsteampassnet and I think this is also a good use case that on each login it synces with LDAP

**Comment by alozano-sct** [comment]
Hi, i have same problem with OpenLdap and migration from 2.17.xx
When i configured LDAP and test in the same page, i can see logs on my ldap server and the test its ok.
But when i try to login, always obtained user or password is incorrect.

**Comment by nilsteampassnet** [comment]
@ismaelvillalba 
Please update to latest commit.
I have passed some fixes regarding AD.

**Comment by ismaelvillalba** [comment]
@nilsteampassnet  I updated the version to TeamPass 3.0.10 successfully and configured the server from 0 again, but I still have the same problem. In the LDAP configuration I can correctly test the users but when I want to synchronize them it appears as "Done", and it does not load anything.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
