### ISSUE TITLE
Mysqli Centos 6

### ISSUE THREAD

**Issue by David7660** [nilsteampassnet/TeamPass#859]
Hi,

I have a problem installing Teampass on a Centos 6 server.

When I foloow the process to install Teampass on ipserv/teampass/install/install.php, I have a problem with the function mysqli.

On my server I have installed php54 ans the command php -m return thath mysqli is enable.

If someone have an idea or installed teampass on Centos I'm really interessed

Thx :)

**Comment by nilsteampassnet** [comment]
What version?
Have you checked #801

**Comment by David7660** [comment]
With the version 2.1.22

Yes I saw this post but it didn't fix anything.

Maybe on CentOs it is different ?

**Comment by David7660** [comment]
On the website http://php.net/manual/fr/mysqli.installation.php

I can see that mysqli is present by default. So i don't understand

**Comment by nilsteampassnet** [comment]
Can you give the error you get?

**Comment by David7660** [comment]
The error is on the screenshot.

Maybe you want an another log ?

**Comment by nilsteampassnet** [comment]
I don't see any screenshot

**Comment by David7660** [comment]
https://cloud.githubusercontent.com/assets/10684350/5887623/722cd8ea-a3dc-11e4-8dff-90c5de435034.png

There :)

**Comment by nilsteampassnet** [comment]
Please confirm if you have run `apt-get install php5-mysqlnd`

**Comment by David7660** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/10684350/5887874/c5ed4f22-a3e7-11e4-870b-2fc715a2f37c.png)

just there

**Comment by David7660** [comment]
Hi,

I fixed my issue, I just upgraded my php5.4 to php5.5 :)

Thanks for your help

**Comment by corux** [comment]
I'm having the same problem on CentOS 7 (using php 5.4).
The issue can also be solved by replacing `mysqli_fetch_all` with `mysqli_fetch_row` in install.php and install.js. These are the only places that `mysqli_fetch_all` is used, anyway.

**Comment by GaneshKandu** [comment]
Hi, Getting Same Error
![screenshot-192 168 58 139 2016-01-11 15-12-43](https://cloud.githubusercontent.com/assets/12833130/12230530/54635176-b877-11e5-8ebb-e5463272709b.png)

on PHP 5.5 MySQL 5.5
CentOS

**Comment by nilsteampassnet** [comment]
​Please install php5-mysqlnd

**Comment by vchrizz** [comment]
hi, same error here with latest teampass (2.1.26-patch-1) on debian 8.6 php 5.6.29 mysqld 5.5.53
installed php5-mysqlnd (5.6.29) instead php5-mysql (5.6.29) but still the error persists.
<?php function_exists(mysqli_fetch_all) ?> in an own script returns: 1

**Comment by sanj3k** [comment]
I have the same problem with CentOS 6.9

Php modules until mysqli and mysqlnd
![bildschirmfoto 2017-08-10 um 13 41 54](https://user-images.githubusercontent.com/21160640/29168954-b74fcfb4-7dd1-11e7-8d0e-89d1182f6f37.png)

![bildschirmfoto 2017-08-10 um 13 42 39](https://user-images.githubusercontent.com/21160640/29168966-cd4def58-7dd1-11e7-814b-f44cc4551f3b.png)

Which log output do you need?
